# Generated by Django 2.0.1 on 2018-01-26 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_postandcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postandcomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='postandcomment',
            name='post',
        ),
        migrations.DeleteModel(
            name='PostAndComment',
        ),
    ]
